name: knightassist
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  animated_custom_dropdown: ^3.0.0
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.1
  chip_list: ^2.4.4+8
  clock: ^1.1.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.1.0
  flutter_hooks: ^0.20.5
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  google_fonts: 6.1.0 # This is currently hardcoded due to an issue with the newest version of the package
  hooks_riverpod: ^2.4.10
  intl: ^0.19.0
  json_annotation: ^4.8.1
  qr_code_scanner: ^1.0.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.2
  time: ^2.1.4
  url_launcher: ^6.2.5
  

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets: 
    - assets/KnightAssistCoATransparent.png
    - assets/KnightAssistCoA2.png
    - assets/KnightAssistCoA3.png
    - assets/example.png
    - assets/profile pictures/icon_apple.png
    - assets/profile pictures/icon_cat.png
    - assets/profile pictures/icon_cookie.png
    - assets/profile pictures/icon_controller.png
    - assets/profile pictures/icon_heart.png
    - assets/profile pictures/icon_leaf.png
    - assets/profile pictures/icon_musicnote.png
    - assets/profile pictures/icon_paintbrush.png
    - assets/profile pictures/icon_planet.png
    - assets/profile pictures/icon_soccer.png
    - assets/profile pictures/icon_weight.png
    - assets/icon/icon.png
    - assets/icon/icontransparent.png
    - assets/orgdefaultbackground.png
    - assets/ca/lets-encrypt-r3.pem
